"""
Django settings for tracking project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q5^i35qr%wmkhniazglz_1$6e@e-88j1be(h(11pu*ciic-pg-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paths',
    'reports',
    'alerts',
    'maneuver',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tracking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/Users/Ruben Melo/Documents/Projects/tracking_v2/tracking/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tracking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

DB_PARAMS = {
    "server": "190.242.119.122",
    "user": "SioPlatformUsr",
    "password": "S10Pl@tf0rm",
    "db": "ITG-Sio"
}

CONN_STRING = """
    Driver={{SQL Server}};
    Server={0};
    Database={1};
    UID={2};
    PWD={3};
""".format(DB_PARAMS["server"], DB_PARAMS["db"], DB_PARAMS["user"], DB_PARAMS["password"])

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/


STATIC_URL = '/Users/Ruben Melo/Documents/Projects/tracking_v2/tracking/static/'

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
        '/Users/Ruben Melo/Documents/Projects/tracking_v2/tracking/static/',
]

VESSEL_CINFIGURATION_URL = "http://nautilus.intertug.com:8080/api/vesselconfiguration/"
VESSELS_POSITION_URL = "http://190.242.119.122:82/sioservices/daqonboardservice.asmx/GetVesselsPosition?"
VISUAL_CONFIGURATION_URL = "http://nautilus.intertug.com:8080/api/visualconfiguration/"
MAP_CONFIGURATION_URL = "http://nautilus.intertug.com:8080/api/mapconfiguration/"
DAQ_VALUE_URL = "http://190.242.119.122:82/sioservices/daqonboardservice.asmx/GetDaqValue?"
VESSEL_GPS_DATA_URL = "http://190.242.119.122:82/sioservices/daqonboardservice.asmx/GetVesselGpsData?"
ALARMS_LOG_URL = "http://nautilus.intertug.com:8080/api/alarmsLog/"
CREATE_SESSION_URL = "http://190.242.119.122:82/sioservices/SioGeneralService.asmx/CreateSession?"
APPLICATION_ID = "24649159-AF50-4C6F-9EBE-474F4E7BEF57"